### ISSUE TITLE
リソース設計を作成

### ISSUE THREAD

**Issue by su-su-su-su** [su-su-su-su/yoyaku-hub#48]
### OAuth 2.0 ログイン & 認証
| Method | Path | Description |
|--------|------|-------------|
| GET | /auth/stylists/:provider/callback | OAuth 2.0によるログイン処理、スタイリスト作成処理 |
| GET | /auth/customers/:provider/callback | OAuth 2.0によるログイン処理、カスタマー作成処理 |

アカウントの作成はGoogleアカウントから作れるようにしています。
Googleのアカウントがない方もいるので、メールアドレス、パスワードでも作成できるようにしています。

### スタイリスト認証関連
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/sign_up | スタイリストサインアップ |
| GET | /stylists/sign_in | スタイリストサインイン画面を表示 |
| POST | /stylists/sign_in | スタイリストサインイン |
| DELETE | /stylists/sign_out | スタイリストサインアウト |

### スタイリストのダッシュボードとプロフィール関連
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/dashboard | スタイリストトップページを表示 |
| POST | /stylists/profile | スタイリスト情報登録 |
| GET | /stylists/profile | スタイリスト情報 |

### スタイリストの予約管理
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/schedules/:date | 予約表画面を表示 |
| PATCH | /stylists/reservation_limits/{reservation_limit_id} | 時間別の受付可能数を変更 |
| GET | /stylists/reservations/{reservation_id} | 予約の詳細を表示 |
| PATCH | /stylists/reservations/{reservation_id} | 予約の変更 |
| DELETE | /stylists/reservations/{reservation_id} | 予約のキャンセル |
| GET | /stylists/reservations/new | 予約の登録画面を表示 |
| POST | /stylists/reservations | 予約の登録 |

### 検索機能
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/customers?name={検索クエリ} | お客様検索 |

スタイリストが予約登録にお客様の検索をする時に使います。

### メニュー設定
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/menus_settings | メニュー設定画面を表示 |
| POST | /stylists/menus_settings | メニュー設定 |
| PATCH | /stylists/menus_settings/{menu_id} | メニュー更新 |

### スタイリストのシフト管理
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/shift_settings | シフト画面を表示 |
| POST | /stylists/shift_settings/working_hours | 営業時間登録 |
| POST | /stylists/shift_settings/holidays | 休業日登録 |
| POST | /stylists/shift_settings/reservation_limits | 受付可能数登録 |
| PATCH | /stylists/shift_settings/{working_hour_id} | 営業時間更新 |
| PATCH | /stylists/shift_settings/{holiday_id} | 休業日更新 |
| PATCH | /stylists/shift_settings/{reservation_limit_id} | 受付可能数更新 |
| GET | /stylists/shift_settings/:year/:month | 毎月の受付設定を表示 |
| POST | /stylists/shift_settings/:year/:month | 毎月の受付設定登録 |
| PATCH | /stylists/shift_settings/:year/:month | 毎月の受付設定更新 |

``` json
"shift_data": [
  {
    "date": "2024-10-01",
    "target_date": {
      "start_time": "09:00",
      "end_time": "18:00"
    },
    "is_holiday": false,
    "max_reservations": 2
  },
  {
    "date": "2024-10-02",
    "target_date": {
      "start_time": "10:00",
      "end_time": "17:00"
    },
    "is_holiday": true,
    "max_reservations": 1
  }
]
```

このJSONは、毎月の受付設定を送信するときに使ように考えています。各日付に対して、その日の営業時間、休業日、最大予約数を1つのリクエストで登録、更新できるようにします。

### カスタマー認証関連
| Method | Path | Description |
|--------|------|-------------|
| GET | /customers/sign_up | カスタマー会員登録を表示 |
| GET | /customers/sign_in | カスタマーログイン画面を表示 |
| POST | /customers/sign_in | カスタマーログイン |
| DELETE | /customers/sign_out | カスタマーログアウト |

### カスタマートップページ & プロフィール関連
| Method | Path | Description |
|--------|------|-------------|
| GET | /customers/dashboard | カスタマートップページを表示 |
| POST | /customers/profile | カスタマー情報登録 |
| GET | /customers/profile | カスタマー情報を表示 |

### カスタマーの予約関連
| Method | Path | Description |
|--------|------|-------------|
| GET | /customers/stylists | スタイリスト選択を表示 |
| GET | /customers/stylists/{stylist_id}/menus | メニュー画面を表示 |
| GET | /customers/stylists/{stylist_id}/menus/{menu_id}/weekly | 日時選択画面を表示 |
| GET | /customers/reservations/confirm | 予約確定確認画面を表示 |
| POST | /customers/reservations | 予約登録 |
| GET | /customers/reservations | 予約履歴を表示 |
| GET | /customers/reservations/{reservation_id} | 予約の詳細を表示 |
| PATCH | /customers/reservations/{reservation_id} | 予約の変更 |
| DELETE | /customers/reservations/{reservation_id} | 予約のキャンセル |

### 規約とプライバシー
| Method | Path | Description |
|--------|------|-------------|
| GET | /privacy | プライバシーポリシーを表示 |
| GET | /terms | 利用規約を表示 |

<details>
  <summary>1度目の提出</summary>

 ### OAuth 2.0 ログイン & 認証

| Method | Path | Description |
|--------|------|-------------|
| GET | /auth/stylists/:provider/callback | OAuth 2.0によるログイン処理、スタイリスト作成処理 |
| GET | /auth/customers/:provider/callback | OAuth 2.0によるログイン処理、カスタマー作成処理 |

アカウントの作成はGoogleアカウントから作れるようにしています。
Googleのアカウントがない方もいるので、メールアドレス、パスワードでも作成できるようにしています。

### スタイリスト認証関連
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/sign_up | スタイリストサインアップ |
| GET | /stylists/sign_in | スタイリストサインイン画面を表示 |
| POST | /stylists/sign_in | スタイリストサインイン |
| DELETE | /stylists/sign_out | スタイリストサインアウト |

### スタイリストのダッシュボードとプロフィール関連
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/dashboard | スタイリストトップページを表示 |
| POST | /stylists/profile | スタイリスト情報登録 |
| GET | /stylists/profile | スタイリスト情報 |

### スタイリストの予約管理
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/schedules/:year/:month/:day | 予約表画面を表示 |
| PATCH | /stylists/appointment_limits/{appointment_limit_id} | 時間別の受付可能数を変更 |
| GET | /stylists/appointments/{appointment_id} | 予約の詳細を表示 |
| PATCH | /stylists/appointments/{appointment_id} | 予約の変更 |
| DELETE | /stylists/appointments/{appointment_id} | 予約のキャンセル |
| GET | /stylists/appointments/new | 予約の登録画面を表示 |
| POST | /stylists/appointments/{customer_id} | 予約の登録 |

### 検索機能
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/customers/search?name={検索クエリ} | お客様検索 |

スタイリストが予約登録にお客様の検索をする時に使います。

### メニュー設定
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/menus_settings | メニュー設定画面を表示 |
| POST | /stylists/menus_settings | メニュー設定 |
| PATCH | /stylists/menus_settings/{menu_id} | メニュー更新 |
| DELETE | /stylists/menus_settings/{menu_id} | メニュー削除 |

### スタイリストのシフト管理
| Method | Path | Description |
|--------|------|-------------|
| GET | /stylists/shift_settings | シフト画面を表示 |
| POST | /stylists/shift_settings/working_hours | 営業時間登録 |
| POST | /stylists/shift_settings/holidays | 休業日登録 |
| POST | /stylists/shift_settings/appointment_limits | 受付可能数登録 |
| PATCH | /stylists/shift_settings/{working_hour_id} | 営業時間更新 |
| PATCH | /stylists/shift_settings/{holiday_id} | 休業日更新 |
| PATCH | /stylists/shift_settings/{appointment_limit_id} | 受付可能数更新 |
| GET | /stylists/shift_settings/:year/:month | 毎月の受付設定を表示 |
| POST | /stylists/shift_settings/:year/:month | 毎月の受付設定登録 |
| PATCH | /stylists/shift_settings/:year/:month | 毎月の受付設定更新 |

``` json
"shift_data": [
  {
    "date": "2024-10-01",
    "working_hours": {
      "start_time": "09:00",
      "end_time": "18:00"
    },
    "is_holiday": false,
    "max_appointments": 2
  },
  {
    "date": "2024-10-02",
    "working_hours": {
      "start_time": "10:00",
      "end_time": "17:00"
    },
    "is_holiday": true,
    "max_appointments": 1
  }
]
```

このJSONは、毎月の受付設定を送信するときに使ように考えています。各日付に対して、その日の営業時間、休業日、最大予約数を1つのリクエストで登録、更新できるようにします。

### カスタマー認証関連
| Method | Path | Description |
|--------|------|-------------|
| GET | /customers/sign_up | カスタマー会員登録を表示 |
| GET | /customers/sign_in | カスタマーログイン画面を表示 |
| POST | /customers/sign_in | カスタマーログイン |
| DELETE | /customers/sign_out | カスタマーログアウト |

### カスタマートップページ & プロフィール関連
| Method | Path | Description |
|--------|------|-------------|
| GET | /customers/dashboard | カスタマートップページを表示 |
| POST | /customers/profile | カスタマー情報登録 |
| GET | /customers/profile | カスタマー情報を表示 |

### カスタマーの予約関連
| Method | Path | Description |
|--------|------|-------------|
| GET | /customers/appointments/stylists | スタイリスト選択を表示 |
| GET | /customers/appointments/{stylist_id}/menus | メニュー画面を表示 |
| GET | /customers/appointments/{stylist_id}/{menu_id}/datetime | 日時選択画面を表示 |
| GET | /customers/appointments/{stylist_id}/{menu_id}/datetime/confirm | 予約確定確認画面を表示 |
| POST | /customers/appointments/{stylist_id} | 予約登録 |
| GET | /customers/appointments | 予約履歴を表示 |
| GET | /customers/appointments/{appointment_id} | 予約の詳細を表示 |
| PATCH | /customers/appointments/{appointment_id} | 予約の変更 |
| DELETE | /customers/appointments/{appointment_id} | 予約のキャンセル |

### 規約とプライバシー
| Method | Path | Description |
|--------|------|-------------|
| GET | /privacy | プライバシーポリシーを表示 |
| GET | /terms | 利用規約を表示 |
</details>

**Comment by maedana** [comment]
気になったこと書きますね。

### スタイリストの予約管理
- 予約表は`/stylists/schedules/:year/:month/:day`ですが、理由がなければ`/stylists/schedules/:date`のようにして、例えばyyyy-mm-dd式で受け取ってもいいかなーと思いました。サーバ側で`'2024-10-01'.to_date`みたいにするとDate型に出来るので、年月日ごとにパラメタ別れているより扱いやすい気がしました。
- 予約の登録ですが、`/stylists/appointments/{customer_id}`でなくシンプルに`/stylists/appointments/`でよいかと思います。画面上予約する顧客はフォームのプルダウンで選ぶようですし、リクエストボディでいいと思います。URIに入れるメリットがないかと。もし実現するならプルダウンの値を変更するたびにformタグのaction属性を書き換える、みたいなややこしい対応が必要かと思います。

### スタイリストの顧客検索機能
- `/stylists/customers/search?name={検索クエリ}`ですが、REST的に考えてsearchなくても`/stylists/customers?name={検索クエリ}`でいいんじゃないですかね

### スタイリストのメニュー設定
- リソースの問題でなく実装の注意点ですが、メニュー削除は気をつけて実装しないと紐付いている予約ごとバッサリ消えたりとかしそうですね。基本的にまだ一度も利用されていないメニューしか消せないとか、削除ではなく未使用フラグ立てるだけにするとか注意が必要になりそうだな、と思いました。

### カスタマーの予約関連
- URL的に顧客側のスタイリスト選択が必須に見えますが必須なんでしょうか? 特にはじめて行くような美容室だと選びにくいというか誰でもOKみたいにすることが個人的には多くて気になりました。メニューを先に選ばせてスタイリストお任せパターンもあっていいのかなーと。実装するもの減らす、という意味では最初はなくていいと思います。
- メニュー画面を表示,日時選択画面を表示,予約確定確認画面を表示,予約登録のURIがREST的に違和感ある感じですねー。
  - 例えば`/customers/appointments/{stylist_id}/menus` ですと、/customers/appointments/1/menus みたいになるのでIDが1のappointmentsに紐づくmenu一覧みたいに見えてしまいます。見直してみて欲しいです。

以上いかがでしょうか

**Comment by su-su-su-su** [comment]
## スタイリストの予約管理

> 予約表は`/stylists/schedules/:year/:month/:day`ですが、理由がなければ`/stylists/schedules/:date`のようにして、例えばyyyy-mm-dd式で受け取ってもいいかなーと思いました。サーバ側で`'2024-10-01'.to_date`みたいにするとDate型に出来るので、年月日ごとにパラメタ別れているより扱いやすい気がしました。

ありがとうございます。
特定の日のスケジュールが表示できれば十分なので、/stylists/schedules/:year/:month/:dayである必要はありません。ご提案していただいたものの方がわかりやすいので/stylists/schedules/:dateに変更しました。


> 予約の登録ですが、`/stylists/appointments/{customer_id}`でなくシンプルに`/stylists/appointments/`でよいかと思います。画面上予約する顧客はフォームのプルダウンで選ぶようですし、リクエストボディでいいと思います。URIに入れるメリットがないかと。もし実現するならプルダウンの値を変更するたびにformタグのaction属性を書き換える、みたいなややこしい対応が必要かと思います。

こちらも、/stylists/reservations/{customer_id}から/stylists/reservationsに変更しました。
リクエストボディ内で指定するようにし、「プルダウンの値を変更するたびにformタグのaction属性を書き換える」というのもしてみたいと思います。


### スタイリストの顧客検索機能

> `/stylists/customers/search?name={検索クエリ}`ですが、REST的に考えてsearchなくても`/stylists/customers?name={検索クエリ}`でいいんじゃないですかね

searchを使用しているサービスが多かったため深く考えずに採用していましたが、いただいた提案の通り、/stylists/customers?name={検索クエリ}に変更しました。


### スタイリストのメニュー設定

> リソースの問題でなく実装の注意点ですが、メニュー削除は気をつけて実装しないと紐付いている予約ごとバッサリ消えたりとかしそうですね。基本的にまだ一度も利用されていないメニューしか消せないとか、削除ではなく未使用フラグ立てるだけにするとか注意が必要になりそうだな、と思いました。

確かに、ホットペッパービューティーなどでも削除せず「表示/非表示」を切り替える方法を採用している理由が理解できました。こちらのサービスでもメニューの削除ではなく「非表示」にする仕様に変更し、それに伴いデータベースのメニューテーブルにis_activeカラムを追加しました。


### カスタマーの予約関連

> URL的に顧客側のスタイリスト選択が必須に見えますが必須なんでしょうか? 特にはじめて行くような美容室だと選びにくいというか誰でもOKみたいにすることが個人的には多くて気になりました。メニューを先に選ばせてスタイリストお任せパターンもあっていいのかなーと。実装するもの減らす、という意味では最初はなくていいと思います。

ホットペッパーのようなサービスですとサロンに所属しているスタイリストがおりその中から選ぶ、または誰でもOKとなるのですが、こちらはフリーランスの美容師の予約サービスでサロンが管理して使うというより各美容師が使うことを想定しています。
その為、サロンのような箱がないので誰かを選ぶようになっています。

> メニュー画面を表示,日時選択画面を表示,予約確定確認画面を表示,予約登録のURIがREST的に違和感ある感じですねー。

  > 例えば`/customers/appointments/{stylist_id}/menus` ですと、/customers/appointments/1/menus みたいになるのでIDが1のappointmentsに紐づくmenu一覧みたいに見えてしまいます。見直してみて欲しいです。

ありがとうございます。
ご指摘を受けてみると確かにそうだと感じました。それを踏まえて修正しました。ご確認よろしくお願いいたします。

**Comment by maedana** [comment]
> こちらはフリーランスの美容師の予約サービスでサロンが管理して使うというより各美容師が使うことを想定しています。
その為、サロンのような箱がないので誰かを選ぶようになっています。

うすうすそんな感じはしてましたのでOKです。余談ですけど、かなり前に僕ワーホリで海外滞在していたことがあるんですが、向こうの美容師さんでいい人にあたったことがなく(というかアジア人の髪質って白人とはかなり違うみたいで、そもそも勝手が違うみたいでした)、友達つながりで現地の日本人美容師さんに個人的にお願いして切ってもらったりしてました。もしかしたらそういう人たちにもうまく刺されば便利に使えるのかなって思いました。


他は一旦これで進めてみて何か問題があればまた見直す感じかなと思いました。もし追加で気がついたことが出てきたら後ほどまたコメントするかもです。

**Comment by su-su-su-su** [comment]
> 余談ですけど、かなり前に僕ワーホリで海外滞在していたことがあるんですが、向こうの美容師さんでいい人にあたったことがなく(というかアジア人の髪質って白人とはかなり違うみたいで、そもそも勝手が違うみたいでした)、友達つながりで現地の日本人美容師さんに個人的にお願いして切ってもらったりしてました。もしかしたらそういう人たちにもうまく刺されば便利に使えるのかなって思いました。

ワーホリや留学の経験がないので全くその発想がなかったです。確かに髪質の問題で海外に住んでる日本人は日本人に切ってもらう事が多いみたいですね。
よりニッチなサービスで競合もいなさそうなのでそっちの方が知ってもらえれば使ってもらえるかもですね。そちらの方向性もあるのかと柔軟に考えていきたいと思います。貴重な意見ありがとうございます！

> 他は一旦これで進めてみて何か問題があればまた見直す感じかなと思いました。もし追加で気がついたことが出てきたら後ほどまたコメントするかもです。

ありがとうございます。引き続きよろしくお願いいたします。
